title: Ram Newton A
description: Ram Newton A

username: Ram Newton

email: nope
github_username: RamNewton
twitter_username: ramnewton_a
linkedin_username: ramnewton
dev_username: ramnewton

base_url: ""
